QT += testlib
QT += gui
QT += widgets
QT += serialport
QT += bluetooth
QT += sql
QT += xml
QT += network
QT += usb

CONFIG += qt warn_on depend_includepath testcase


TEMPLATE = app

INCLUDEPATH += ../../src

# Debug libraries
CONFIG(debug, debug|release) {
# OpenSSL
INCLUDEPATH += "C:/Program Files (x86)/OpenSSL-Win32/include"
LIBS += -L"C:/Program Files (x86)/OpenSSL-Win32/lib/VC/x86/MDd" -llibssl -llibcrypto

# POCO
INCLUDEPATH += "C:/Program Files (x86)/Poco/include"
LIBS += -L"C:/Program Files (x86)/Poco/lib" -lPocoFoundationd -lPocoUtild -lPocoCryptod -lPocoNetd -lPocoNetSSLd

# DCMTK
INCLUDEPATH += "C:/Program Files (x86)/DCMTK/include"
LIBS += -L"C:/Users/hoarea/CypressDeps/dcmtk-3.6.8/dcmtk-3.6.8/build-msvc-2022/lib/Debug" -ldcmdata -loflog -lofstd -lws2_32 -lnetapi32 -lwsock32 -ladvapi32 -liphlpapi
}

# Release libraries
CONFIG(release, debug|release) {
# OpenSSL
INCLUDEPATH += "C:/Program Files (x86)/OpenSSL-Win32/include"
LIBS += -L"C:/Program Files (x86)/OpenSSL-Win32/lib/VC/x86/MD" -llibssl -llibcrypto

# POCO
INCLUDEPATH += "C:/Program Files (x86)/Poco/include"
LIBS += -L"C:/Program Files (x86)/Poco/lib" -lPocoFoundation -lPocoUtil -lPocoCrypto -lPocoNet -lPocoNetSSL

# DCMTK
INCLUDEPATH += "C:/Program Files (x86)/DCMTK/include"
LIBS += -L"C:/Users/hoarea/CypressDeps/dcmtk-3.6.8/dcmtk-3.6.8/build-msvc-2022/lib/Release" -ldcmdata -loflog -lofstd -lws2_32 -lnetapi32 -lwsock32 -ladvapi32 -liphlpapi
}

SOURCES +=  tst_frax.cpp \
    ../../src/auxiliary/CRC8.cpp \
    ../../src/auxiliary/Constants.cpp \
    ../../src/auxiliary/Utilities.cpp \
    ../../src/auxiliary/bluetooth_util.cpp \
    ../../src/auxiliary/file_compressor.cpp \
    ../../src/auxiliary/file_utils.cpp \
    ../../src/auxiliary/json_settings.cpp \
    ../../src/auxiliary/network_utils.cpp \
    ../../src/auxiliary/pdf_form_filler.cpp \
    ../../src/auxiliary/tracker5_util.cpp \
    ../../src/auxiliary/validators.cpp \
    ../../src/auxiliary/windows_util.cpp \
    ../../src/config/device_config.cpp \
    ../../src/cypress_application.cpp \
    ../../src/cypress_main_window.cpp \
    ../../src/cypress_session.cpp \
    ../../src/cypress_settings.cpp \
    ../../src/data/access_query_helper.cpp \
    ../../src/data/blood_pressure/measurements/blood_pressure_measurement.cpp \
    ../../src/data/blood_pressure/measurements/watch_bp_measurement.cpp \
    ../../src/data/blood_pressure/tests/blood_pressure_test.cpp \
    ../../src/data/blood_pressure/tests/watch_bp_test.cpp \
    ../../src/data/cdtt/measurements/cdtt_measurement.cpp \
    ../../src/data/cdtt/tests/cdtt_test.cpp \
    ../../src/data/choice_reaction/measurements/choice_reaction_measurement.cpp \
    ../../src/data/choice_reaction/tests/choice_reaction_test.cpp \
    ../../src/data/cimt_vivid_i_measurement.cpp \
    ../../src/data/cimt_vivid_i_test.cpp \
    ../../src/data/dxa/measurements/ap_spine_measurement.cpp \
    ../../src/data/dxa/measurements/dxa_measurement.cpp \
    ../../src/data/dxa/measurements/forearm_measurement.cpp \
    ../../src/data/dxa/measurements/hip_measurement.cpp \
    ../../src/data/dxa/measurements/iva_imaging_measurement.cpp \
    ../../src/data/dxa/measurements/whole_body_measurement.cpp \
    ../../src/data/dxa/tests/dxa_hip_test.cpp \
    ../../src/data/dxa/tests/dxa_test.cpp \
    ../../src/data/ecg/measurements/ecg_measurement.cpp \
    ../../src/data/ecg/measurements/mac5_measurement.cpp \
    ../../src/data/ecg/tests/ecg_test.cpp \
    ../../src/data/ecg/tests/mac5_test.cpp \
    ../../src/data/excel_query_helper.cpp \
    ../../src/data/frax/frax_helper.cpp \
    ../../src/data/frax/measurements/frax_measurement.cpp \
    ../../src/data/frax/tests/frax_test.cpp \
    ../../src/data/grip_strength/measurements/grip_strength_measurement.cpp \
    ../../src/data/grip_strength/tests/grip_strength_test.cpp \
    ../../src/data/hearing/measurements/hearcon_measurement.cpp \
    ../../src/data/hearing/measurements/hearing_measurement.cpp \
    ../../src/data/hearing/tests/hearcon_test.cpp \
    ../../src/data/hearing/tests/hearing_test.cpp \
    ../../src/data/measurement.cpp \
    ../../src/data/retinal_camera/database_manager.cpp \
    ../../src/data/retinal_camera/oct_measurement.cpp \
    ../../src/data/retinal_camera/oct_test.cpp \
    ../../src/data/retinal_camera/retinal_camera_measurement.cpp \
    ../../src/data/retinal_camera/retinal_camera_test.cpp \
    ../../src/data/spirometer/measurements/easyone_measurement.cpp \
    ../../src/data/spirometer/measurements/spirometer_measurement.cpp \
    ../../src/data/spirometer/tests/easyone_test.cpp \
    ../../src/data/spirometer/tests/spirometer_test.cpp \
    ../../src/data/temperature/measurements/temperature_measurement.cpp \
    ../../src/data/temperature/tests/temperature_test.cpp \
    ../../src/data/test_base.cpp \
    ../../src/data/tonometer/measurements/tonometer_measurement.cpp \
    ../../src/data/tonometer/tests/tonometer_test.cpp \
    ../../src/data/ultrasound/vivid_iq_measurement.cpp \
    ../../src/data/ultrasound/vivid_iq_test.cpp \
    ../../src/data/weigh_scale/measurements/weight_measurement.cpp \
    ../../src/data/weigh_scale/tests/weigh_scale_test.cpp \
    ../../src/dialogs/audiometer_dialog.cpp \
    ../../src/dialogs/blood_pressure_dialog.cpp \
    ../../src/dialogs/cdtt_dialog.cpp \
    ../../src/dialogs/choice_reaction_dialog.cpp \
    ../../src/dialogs/cimt_vivid_i_dialog.cpp \
    ../../src/dialogs/cimt_vivid_iq_dialog.cpp \
    ../../src/dialogs/dialog_base.cpp \
    ../../src/dialogs/dialog_factory.cpp \
    ../../src/dialogs/dxa_dialog.cpp \
    ../../src/dialogs/dxa_hip_dialog.cpp \
    ../../src/dialogs/easyone_dialog.cpp \
    ../../src/dialogs/ecg_dialog.cpp \
    ../../src/dialogs/frax_dialog.cpp \
    ../../src/dialogs/general_proxy_form_dialog.cpp \
    ../../src/dialogs/grip_strength_dialog.cpp \
    ../../src/dialogs/hearcon_dialog.cpp \
    ../../src/dialogs/mac5_dialog.cpp \
    ../../src/dialogs/oct_dialog.cpp \
    ../../src/dialogs/ora_dialog.cpp \
    ../../src/dialogs/retinal_camera_dialog.cpp \
    ../../src/dialogs/spirometer_dialog.cpp \
    ../../src/dialogs/tonometer_dialog.cpp \
    ../../src/dialogs/vivid_iq_dialog.cpp \
    ../../src/dialogs/watch_bp_dialog.cpp \
    ../../src/dialogs/weigh_scale_dialog.cpp \
    ../../src/dicom/dcm_recv.cpp \
    ../../src/dicom/dicom_directory_watcher.cpp \
    ../../src/managers/audiometer/audiometer_manager.cpp \
    ../../src/managers/audiometer/hearcon_manager.cpp \
    ../../src/managers/blood_pressure/blood_pressure_manager.cpp \
    ../../src/managers/blood_pressure/bpm_message.cpp \
    ../../src/managers/blood_pressure/bpm_messages.cpp \
    ../../src/managers/blood_pressure/bptru_200_driver.cpp \
    ../../src/managers/blood_pressure/watch_bp_manager.cpp \
    ../../src/managers/cdtt/cdtt_manager.cpp \
    ../../src/managers/choice_reaction/choice_reaction_manager.cpp \
    ../../src/managers/dxa/apex_database_helper.cpp \
    ../../src/managers/dxa/dxa_hip_manager.cpp \
    ../../src/managers/dxa/dxa_manager.cpp \
    ../../src/managers/ecg/ecg_manager.cpp \
    ../../src/managers/ecg/mac5_manager.cpp \
    ../../src/managers/emr/emr_plugin_writer.cpp \
    ../../src/managers/frax/frax_manager.cpp \
    ../../src/managers/general_proxy_form/general_proxy_manager.cpp \
    ../../src/managers/grip_strength/grip_strength_manager.cpp \
    ../../src/managers/grip_strength/paradox_reader.cpp \
    ../../src/managers/manager_base.cpp \
    ../../src/managers/participant_report/participant_report_manager.cpp \
    ../../src/managers/retinal_camera/oct_manager.cpp \
    ../../src/managers/retinal_camera/retinal_camera_manager.cpp \
    ../../src/managers/serial_port/serial_port_manager.cpp \
    ../../src/managers/spirometer/easyone_manager.cpp \
    ../../src/managers/spirometer/spirometer_manager.cpp \
    ../../src/managers/tonometer/ora_manager.cpp \
    ../../src/managers/tonometer/tonometer_manager.cpp \
    ../../src/managers/ultrasound/vivid_iq_manager.cpp \
    ../../src/managers/ultrasound/vividi_manager.cpp \
    ../../src/managers/weigh_scale/weigh_scale_manager.cpp \
    ../../src/server/cypress_status_request_handler.cpp \
    ../../src/server/default_delete_request_handler.cpp \
    ../../src/server/default_request_handler.cpp \
    ../../src/server/default_status_request_handler.cpp \
    ../../src/server/handlers/audiometer/audiometer_request_handler.cpp \
    ../../src/server/handlers/audiometer/audiometer_status_request_handler.cpp \
    ../../src/server/handlers/audiometer/hearcon_request_handler.cpp \
    ../../src/server/handlers/audiometer/hearcon_status_request_handler.cpp \
    ../../src/server/handlers/blood_pressure/blood_pressure_request_handler.cpp \
    ../../src/server/handlers/blood_pressure/blood_pressure_status_request_handler.cpp \
    ../../src/server/handlers/blood_pressure/watch_bp_request_handler.cpp \
    ../../src/server/handlers/blood_pressure/watch_bp_status_request_handler.cpp \
    ../../src/server/handlers/cdtt/cdtt_request_handler.cpp \
    ../../src/server/handlers/cdtt/cdtt_status_request_handler.cpp \
    ../../src/server/handlers/choice_reaction/choice_reaction_request_handler.cpp \
    ../../src/server/handlers/choice_reaction/choice_reaction_status_request_handler.cpp \
    ../../src/server/handlers/dxa/dxa_hip_request_handler.cpp \
    ../../src/server/handlers/dxa/dxa_hip_session_request_handler.cpp \
    ../../src/server/handlers/dxa/dxa_hip_status_request_handler.cpp \
    ../../src/server/handlers/dxa/dxa_request_handler.cpp \
    ../../src/server/handlers/dxa/dxa_session_request_handler.cpp \
    ../../src/server/handlers/dxa/dxa_status_request_handler.cpp \
    ../../src/server/handlers/ecg/ecg_request_handler.cpp \
    ../../src/server/handlers/ecg/ecg_status_request_handler.cpp \
    ../../src/server/handlers/ecg/mac5_request_handler.cpp \
    ../../src/server/handlers/ecg/mac5_status_request_handler.cpp \
    ../../src/server/handlers/frax/frax_request_handler.cpp \
    ../../src/server/handlers/frax/frax_status_request_handler.cpp \
    ../../src/server/handlers/general_proxy_consent/general_proxy_consent_request_handler.cpp \
    ../../src/server/handlers/general_proxy_consent/general_proxy_consent_status_request_handler.cpp \
    ../../src/server/handlers/grip_strength/grip_strength_request_handler.cpp \
    ../../src/server/handlers/grip_strength/grip_strength_status_request_handler.cpp \
    ../../src/server/handlers/participant_report/participant_report_request_handler.cpp \
    ../../src/server/handlers/retinal_camera/oct_left_request_handler.cpp \
    ../../src/server/handlers/retinal_camera/oct_left_status_request_handler.cpp \
    ../../src/server/handlers/retinal_camera/oct_right_request_handler.cpp \
    ../../src/server/handlers/retinal_camera/oct_right_status_request_handler.cpp \
    ../../src/server/handlers/retinal_camera/retinal_camera_left_request_handler.cpp \
    ../../src/server/handlers/retinal_camera/retinal_camera_request_handler.cpp \
    ../../src/server/handlers/retinal_camera/retinal_camera_right_request_handler.cpp \
    ../../src/server/handlers/retinal_camera/retinal_camera_status_request_handler.cpp \
    ../../src/server/handlers/signature_pad/signature_pad_request_handler.cpp \
    ../../src/server/handlers/signature_pad/signature_pad_status_request_handler.cpp \
    ../../src/server/handlers/spirometer/easyone_connect_request_handler.cpp \
    ../../src/server/handlers/spirometer/easyone_connect_status_request_handler.cpp \
    ../../src/server/handlers/spirometer/spirometer_request_handler.cpp \
    ../../src/server/handlers/spirometer/spirometer_status_request_handler.cpp \
    ../../src/server/handlers/tonometer/ora_request_handler.cpp \
    ../../src/server/handlers/tonometer/ora_status_request_handler.cpp \
    ../../src/server/handlers/tonometer/tonometer_request_handler.cpp \
    ../../src/server/handlers/tonometer/tonometer_status_request_handler.cpp \
    ../../src/server/handlers/ultrasound/ultrasound_request_handler.cpp \
    ../../src/server/handlers/ultrasound/ultrasound_status_request_handler.cpp \
    ../../src/server/handlers/ultrasound/vivid_iq_request_handler.cpp \
    ../../src/server/handlers/ultrasound/vivid_iq_status_request_handler.cpp \
    ../../src/server/handlers/weigh_scale/weigh_scale_request_handler.cpp \
    ../../src/server/handlers/weigh_scale/weigh_scale_status_request_handler.cpp \
    ../../src/server/instrument_request_handler_factory.cpp \
    ../../src/server/server.cpp \
    ../../src/server/sessions/audiometer_session.cpp \
    ../../src/server/sessions/bpm_session.cpp \
    ../../src/server/sessions/cdtt_session.cpp \
    ../../src/server/sessions/choice_reaction_session.cpp \
    ../../src/server/sessions/dxa/dxa_hip_session.cpp \
    ../../src/server/sessions/dxa/dxa_session.cpp \
    ../../src/server/sessions/easyone_connect_session.cpp \
    ../../src/server/sessions/ecg_session.cpp \
    ../../src/server/sessions/frax_session.cpp \
    ../../src/server/sessions/gen_proxy_session.cpp \
    ../../src/server/sessions/grip_strength_session.cpp \
    ../../src/server/sessions/hearcon_session.cpp \
    ../../src/server/sessions/jtech_session.cpp \
    ../../src/server/sessions/mac5_session.cpp \
    ../../src/server/sessions/oct_session.cpp \
    ../../src/server/sessions/ora_session.cpp \
    ../../src/server/sessions/participant_report_session.cpp \
    ../../src/server/sessions/retinal_camera_session.cpp \
    ../../src/server/sessions/spirometer_session.cpp \
    ../../src/server/sessions/tonometer_session.cpp \
    ../../src/server/sessions/ultrasound_session.cpp \
    ../../src/server/sessions/vivid_iq_session.cpp \
    ../../src/server/sessions/watch_bp_session.cpp \
    ../../src/server/sessions/weigh_scale_session.cpp \
    ../../src/server/utils.cpp \
    ../../src/widgets/apex_transfer_widget.cpp \
    ../../src/widgets/audiometer_manual_entry_form.cpp \
    ../../src/widgets/bpm_manual_entry_form.cpp \
    ../../src/widgets/device_settings/audiometer_settings_widget.cpp \
    ../../src/widgets/device_settings/blood_pressure_settings_widget.cpp \
    ../../src/widgets/device_settings/cdtt_settings_widget.cpp \
    ../../src/widgets/device_settings/choice_reaction_settings_widget.cpp \
    ../../src/widgets/device_settings/dexa_settings_widget.cpp \
    ../../src/widgets/device_settings/ecg_settings_widget.cpp \
    ../../src/widgets/device_settings/frax_settings_widget.cpp \
    ../../src/widgets/device_settings/grip_strength_settings_widget.cpp \
    ../../src/widgets/device_settings/retinal_camera_settings_widget.cpp \
    ../../src/widgets/device_settings/signature_pad_settings_widget.cpp \
    ../../src/widgets/device_settings/spirometer_settings_widget.cpp \
    ../../src/widgets/device_settings/tonometer_settings_widget.cpp \
    ../../src/widgets/device_settings/vivid_i_settings_widget.cpp \
    ../../src/widgets/device_settings/weight_scale_settings_widget.cpp \
    ../../src/widgets/dicom_widget.cpp \
    ../../src/widgets/directory_picker_widget.cpp \
    ../../src/widgets/file_picker_widget.cpp \
    ../../src/widgets/measurement_table.cpp \
    ../../src/widgets/select_ethnicity_dialog.cpp \
    ../../src/widgets/serial_port_picker_widget.cpp \
    ../../src/widgets/serial_port_widget.cpp \
    ../../src/widgets/settings_dialog.cpp \
    ../../src/widgets/submission_buttons.cpp \
    ../../src/widgets/test_info_widget.cpp \
    ../../src/widgets/usb_port_picker.cpp \
    ../../src/widgets/weight_scale_manual_entry_form.cpp \
    fixtures.cpp

HEADERS += \
    ../../src/auxiliary/CRC8.h \
    ../../src/auxiliary/Constants.h \
    ../../src/auxiliary/Utilities.h \
    ../../src/auxiliary/bluetooth_util.h \
    ../../src/auxiliary/file_compressor.h \
    ../../src/auxiliary/file_utils.h \
    ../../src/auxiliary/json_settings.h \
    ../../src/auxiliary/network_utils.h \
    ../../src/auxiliary/pdf_form_filler.h \
    ../../src/auxiliary/tracker5_util.h \
    ../../src/auxiliary/validators.h \
    ../../src/auxiliary/windows_util.h \
    ../../src/config/device_config.h \
    ../../src/cypress_application.h \
    ../../src/cypress_main_window.h \
    ../../src/cypress_session.h \
    ../../src/cypress_settings.h \
    ../../src/data/access_query_helper.h \
    ../../src/data/blood_pressure/measurements/blood_pressure_measurement.h \
    ../../src/data/blood_pressure/measurements/watch_bp_measurement.h \
    ../../src/data/blood_pressure/tests/blood_pressure_test.h \
    ../../src/data/blood_pressure/tests/watch_bp_test.h \
    ../../src/data/cdtt/measurements/cdtt_measurement.h \
    ../../src/data/cdtt/tests/cdtt_test.h \
    ../../src/data/choice_reaction/measurements/choice_reaction_measurement.h \
    ../../src/data/choice_reaction/tests/choice_reaction_test.h \
    ../../src/data/cimt_vivid_i_measurement.h \
    ../../src/data/cimt_vivid_i_test.h \
    ../../src/data/dxa/measurements/ap_spine_measurement.h \
    ../../src/data/dxa/measurements/dxa_measurement.h \
    ../../src/data/dxa/measurements/forearm_measurement.h \
    ../../src/data/dxa/measurements/hip_measurement.h \
    ../../src/data/dxa/measurements/iva_imaging_measurement.h \
    ../../src/data/dxa/measurements/whole_body_measurement.h \
    ../../src/data/dxa/tests/dxa_hip_test.h \
    ../../src/data/dxa/tests/dxa_test.h \
    ../../src/data/ecg/measurements/ecg_measurement.h \
    ../../src/data/ecg/measurements/mac5_measurement.h \
    ../../src/data/ecg/tests/ecg_test.h \
    ../../src/data/ecg/tests/mac5_test.h \
    ../../src/data/excel_query_helper.h \
    ../../src/data/frax/frax_helper.h \
    ../../src/data/frax/measurements/frax_measurement.h \
    ../../src/data/frax/tests/frax_test.h \
    ../../src/data/grip_strength/measurements/grip_strength_measurement.h \
    ../../src/data/grip_strength/tests/grip_strength_test.h \
    ../../src/data/hearing/measurements/hearcon_measurement.h \
    ../../src/data/hearing/measurements/hearing_measurement.h \
    ../../src/data/hearing/tests/hearcon_test.h \
    ../../src/data/hearing/tests/hearing_test.h \
    ../../src/data/measurement.h \
    ../../src/data/retinal_camera/database_manager.h \
    ../../src/data/retinal_camera/oct_measurement.h \
    ../../src/data/retinal_camera/oct_test.h \
    ../../src/data/retinal_camera/retinal_camera_measurement.h \
    ../../src/data/retinal_camera/retinal_camera_test.h \
    ../../src/data/spirometer/measurements/easyone_measurement.h \
    ../../src/data/spirometer/measurements/spirometer_measurement.h \
    ../../src/data/spirometer/tests/easyone_test.h \
    ../../src/data/spirometer/tests/spirometer_test.h \
    ../../src/data/temperature/measurements/temperature_measurement.h \
    ../../src/data/temperature/tests/temperature_test.h \
    ../../src/data/test_base.h \
    ../../src/data/tonometer/measurements/tonometer_measurement.h \
    ../../src/data/tonometer/tests/tonometer_test.h \
    ../../src/data/ultrasound/vivid_iq_measurement.h \
    ../../src/data/ultrasound/vivid_iq_test.h \
    ../../src/data/weigh_scale/measurements/weight_measurement.h \
    ../../src/data/weigh_scale/tests/weigh_scale_test.h \
    ../../src/dialogs/audiometer_dialog.h \
    ../../src/dialogs/blood_pressure_dialog.h \
    ../../src/dialogs/cdtt_dialog.h \
    ../../src/dialogs/choice_reaction_dialog.h \
    ../../src/dialogs/cimt_vivid_i_dialog.h \
    ../../src/dialogs/cimt_vivid_iq_dialog.h \
    ../../src/dialogs/dialog_base.h \
    ../../src/dialogs/dialog_factory.h \
    ../../src/dialogs/dxa_dialog.h \
    ../../src/dialogs/dxa_hip_dialog.h \
    ../../src/dialogs/easyone_dialog.h \
    ../../src/dialogs/ecg_dialog.h \
    ../../src/dialogs/frax_dialog.h \
    ../../src/dialogs/general_proxy_form_dialog.h \
    ../../src/dialogs/grip_strength_dialog.h \
    ../../src/dialogs/hearcon_dialog.h \
    ../../src/dialogs/mac5_dialog.h \
    ../../src/dialogs/oct_dialog.h \
    ../../src/dialogs/ora_dialog.h \
    ../../src/dialogs/retinal_camera_dialog.h \
    ../../src/dialogs/spirometer_dialog.h \
    ../../src/dialogs/tonometer_dialog.h \
    ../../src/dialogs/vivid_iq_dialog.h \
    ../../src/dialogs/watch_bp_dialog.h \
    ../../src/dialogs/weigh_scale_dialog.h \
    ../../src/dicom/dcm_recv.h \
    ../../src/dicom/dicom_directory_watcher.h \
    ../../src/managers/audiometer/audiometer_manager.h \
    ../../src/managers/audiometer/hearcon_manager.h \
    ../../src/managers/blood_pressure/blood_pressure_manager.h \
    ../../src/managers/blood_pressure/bpm_message.h \
    ../../src/managers/blood_pressure/bpm_messages.h \
    ../../src/managers/blood_pressure/bptru_200_driver.h \
    ../../src/managers/blood_pressure/watch_bp_manager.h \
    ../../src/managers/cdtt/cdtt_manager.h \
    ../../src/managers/choice_reaction/choice_reaction_manager.h \
    ../../src/managers/dxa/apex_database_helper.h \
    ../../src/managers/dxa/dxa_hip_manager.h \
    ../../src/managers/dxa/dxa_manager.h \
    ../../src/managers/ecg/ecg_manager.h \
    ../../src/managers/ecg/mac5_manager.h \
    ../../src/managers/emr/emr_plugin_writer.h \
    ../../src/managers/frax/frax_manager.h \
    ../../src/managers/general_proxy_form/general_proxy_manager.h \
    ../../src/managers/grip_strength/grip_strength_manager.h \
    ../../src/managers/grip_strength/paradox_reader.h \
    ../../src/managers/manager_base.h \
    ../../src/managers/participant_report/participant_report_manager.h \
    ../../src/managers/retinal_camera/oct_manager.h \
    ../../src/managers/retinal_camera/retinal_camera_manager.h \
    ../../src/managers/serial_port/serial_port_manager.h \
    ../../src/managers/spirometer/easyone_manager.h \
    ../../src/managers/spirometer/spirometer_manager.h \
    ../../src/managers/tonometer/ora_manager.h \
    ../../src/managers/tonometer/tonometer_manager.h \
    ../../src/managers/ultrasound/vivid_iq_manager.h \
    ../../src/managers/ultrasound/vividi_manager.h \
    ../../src/managers/weigh_scale/weigh_scale_manager.h \
    ../../src/server/Server.h \
    ../../src/server/cypress_status_request_handler.h \
    ../../src/server/default_delete_request_handler.h \
    ../../src/server/default_request_handler.h \
    ../../src/server/default_status_request_handler.h \
    ../../src/server/handlers/audiometer/audiometer_request_handler.h \
    ../../src/server/handlers/audiometer/audiometer_status_request_handler.h \
    ../../src/server/handlers/audiometer/hearcon_request_handler.h \
    ../../src/server/handlers/audiometer/hearcon_status_request_handler.h \
    ../../src/server/handlers/blood_pressure/blood_pressure_request_handler.h \
    ../../src/server/handlers/blood_pressure/blood_pressure_status_request_handler.h \
    ../../src/server/handlers/blood_pressure/watch_bp_request_handler.h \
    ../../src/server/handlers/blood_pressure/watch_bp_status_request_handler.h \
    ../../src/server/handlers/cdtt/cdtt_request_handler.h \
    ../../src/server/handlers/cdtt/cdtt_status_request_handler.h \
    ../../src/server/handlers/choice_reaction/choice_reaction_request_handler.h \
    ../../src/server/handlers/choice_reaction/choice_reaction_status_request_handler.h \
    ../../src/server/handlers/dxa/dxa_hip_request_handler.h \
    ../../src/server/handlers/dxa/dxa_hip_session_request_handler.h \
    ../../src/server/handlers/dxa/dxa_hip_status_request_handler.h \
    ../../src/server/handlers/dxa/dxa_request_handler.h \
    ../../src/server/handlers/dxa/dxa_session_request_handler.h \
    ../../src/server/handlers/dxa/dxa_status_request_handler.h \
    ../../src/server/handlers/ecg/ecg_request_handler.h \
    ../../src/server/handlers/ecg/ecg_status_request_handler.h \
    ../../src/server/handlers/ecg/mac5_request_handler.h \
    ../../src/server/handlers/ecg/mac5_status_request_handler.h \
    ../../src/server/handlers/frax/frax_request_handler.h \
    ../../src/server/handlers/frax/frax_status_request_handler.h \
    ../../src/server/handlers/general_proxy_consent/general_proxy_consent_request_handler.h \
    ../../src/server/handlers/general_proxy_consent/general_proxy_consent_status_request_handler.h \
    ../../src/server/handlers/grip_strength/grip_strength_request_handler.h \
    ../../src/server/handlers/grip_strength/grip_strength_status_request_handler.h \
    ../../src/server/handlers/participant_report/participant_report_request_handler.h \
    ../../src/server/handlers/retinal_camera/oct_left_request_handler.h \
    ../../src/server/handlers/retinal_camera/oct_left_status_request_handler.h \
    ../../src/server/handlers/retinal_camera/oct_right_request_handler.h \
    ../../src/server/handlers/retinal_camera/oct_right_status_request_handler.h \
    ../../src/server/handlers/retinal_camera/retinal_camera_left_request_handler.h \
    ../../src/server/handlers/retinal_camera/retinal_camera_request_handler.h \
    ../../src/server/handlers/retinal_camera/retinal_camera_right_request_handler.h \
    ../../src/server/handlers/retinal_camera/retinal_camera_status_request_handler.h \
    ../../src/server/handlers/signature_pad/signature_pad_request_handler.h \
    ../../src/server/handlers/signature_pad/signature_pad_status_request_handler.h \
    ../../src/server/handlers/spirometer/easyone_connect_request_handler.h \
    ../../src/server/handlers/spirometer/easyone_connect_status_request_handler.h \
    ../../src/server/handlers/spirometer/spirometer_request_handler.h \
    ../../src/server/handlers/spirometer/spirometer_status_request_handler.h \
    ../../src/server/handlers/tonometer/ora_request_handler.h \
    ../../src/server/handlers/tonometer/ora_status_request_handler.h \
    ../../src/server/handlers/tonometer/tonometer_request_handler.h \
    ../../src/server/handlers/tonometer/tonometer_status_request_handler.h \
    ../../src/server/handlers/ultrasound/ultrasound_request_handler.h \
    ../../src/server/handlers/ultrasound/ultrasound_status_request_handler.h \
    ../../src/server/handlers/ultrasound/vivid_iq_request_handler.h \
    ../../src/server/handlers/ultrasound/vivid_iq_status_request_handler.h \
    ../../src/server/handlers/weigh_scale/weigh_scale_request_handler.h \
    ../../src/server/handlers/weigh_scale/weigh_scale_status_request_handler.h \
    ../../src/server/instrument_request_handler_factory.h \
    ../../src/server/sessions/audiometer_session.h \
    ../../src/server/sessions/bpm_session.h \
    ../../src/server/sessions/cdtt_session.h \
    ../../src/server/sessions/choice_reaction_session.h \
    ../../src/server/sessions/dxa/dxa_hip_session.h \
    ../../src/server/sessions/dxa/dxa_session.h \
    ../../src/server/sessions/easyone_connect_session.h \
    ../../src/server/sessions/ecg_session.h \
    ../../src/server/sessions/frax_session.h \
    ../../src/server/sessions/gen_proxy_session.h \
    ../../src/server/sessions/grip_strength_session.h \
    ../../src/server/sessions/hearcon_session.h \
    ../../src/server/sessions/jtech_session.h \
    ../../src/server/sessions/mac5_session.h \
    ../../src/server/sessions/oct_session.h \
    ../../src/server/sessions/ora_session.h \
    ../../src/server/sessions/participant_report_session.h \
    ../../src/server/sessions/retinal_camera_session.h \
    ../../src/server/sessions/spirometer_session.h \
    ../../src/server/sessions/tonometer_session.h \
    ../../src/server/sessions/ultrasound_session.h \
    ../../src/server/sessions/vivid_iq_session.h \
    ../../src/server/sessions/watch_bp_session.h \
    ../../src/server/sessions/weigh_scale_session.h \
    ../../src/server/utils.h \
    ../../src/widgets/apex_transfer_widget.h \
    ../../src/widgets/audiometer_manual_entry_form.h \
    ../../src/widgets/bpm_manual_entry_form.h \
    ../../src/widgets/device_settings/audiometer_settings_widget.h \
    ../../src/widgets/device_settings/blood_pressure_settings_widget.h \
    ../../src/widgets/device_settings/cdtt_settings_widget.h \
    ../../src/widgets/device_settings/choice_reaction_settings_widget.h \
    ../../src/widgets/device_settings/dexa_settings_widget.h \
    ../../src/widgets/device_settings/ecg_settings_widget.h \
    ../../src/widgets/device_settings/frax_settings_widget.h \
    ../../src/widgets/device_settings/grip_strength_settings_widget.h \
    ../../src/widgets/device_settings/retinal_camera_settings_widget.h \
    ../../src/widgets/device_settings/signature_pad_settings_widget.h \
    ../../src/widgets/device_settings/spirometer_settings_widget.h \
    ../../src/widgets/device_settings/tonometer_settings_widget.h \
    ../../src/widgets/device_settings/vivid_i_settings_widget.h \
    ../../src/widgets/device_settings/weight_scale_settings_widget.h \
    ../../src/widgets/dicom_widget.h \
    ../../src/widgets/directory_picker_widget.h \
    ../../src/widgets/file_picker_widget.h \
    ../../src/widgets/measurement_table.h \
    ../../src/widgets/select_ethnicity_dialog.h \
    ../../src/widgets/serial_port_picker_widget.h \
    ../../src/widgets/serial_port_widget.h \
    ../../src/widgets/settings_dialog.h \
    ../../src/widgets/submission_buttons.h \
    ../../src/widgets/test_info_widget.h \
    ../../src/widgets/usb_port_picker.h \
    ../../src/widgets/weight_scale_manual_entry_form.h

RESOURCES += \
    ../../src/dialogs/cypress.qrc

FORMS += \
    ../../src/cypress_main_window.ui \
    ../../src/dialogs/audiometer_dialog.ui \
    ../../src/dialogs/blood_pressure_dialog.ui \
    ../../src/dialogs/cdtt_dialog.ui \
    ../../src/dialogs/choice_reaction_dialog.ui \
    ../../src/dialogs/cimt_vivid_i_dialog.ui \
    ../../src/dialogs/cimt_vivid_iq_dialog.ui \
    ../../src/dialogs/dxa_dialog.ui \
    ../../src/dialogs/dxa_hip_dialog.ui \
    ../../src/dialogs/easyone_dialog.ui \
    ../../src/dialogs/ecg_dialog.ui \
    ../../src/dialogs/frax_dialog.ui \
    ../../src/dialogs/general_proxy_form_dialog.ui \
    ../../src/dialogs/grip_strength_dialog.ui \
    ../../src/dialogs/hearcon_dialog.ui \
    ../../src/dialogs/mac5_dialog.ui \
    ../../src/dialogs/oct_dialog.ui \
    ../../src/dialogs/ora_dialog.ui \
    ../../src/dialogs/retinal_camera_dialog.ui \
    ../../src/dialogs/runnable_dialog.ui \
    ../../src/dialogs/spirometer_dialog.ui \
    ../../src/dialogs/thermometerdialog.ui \
    ../../src/dialogs/tonometer_dialog.ui \
    ../../src/dialogs/vivid_iq_dialog.ui \
    ../../src/dialogs/watch_bp_dialog.ui \
    ../../src/dialogs/weigh_scale_dialog.ui \
    ../../src/widgets/apex_transfer_widget.ui \
    ../../src/widgets/audiometer_manual_entry_form.ui \
    ../../src/widgets/bpm_manual_entry_form.ui \
    ../../src/widgets/device_settings/audiometer_settings_widget.ui \
    ../../src/widgets/device_settings/blood_pressure_settings_widget.ui \
    ../../src/widgets/device_settings/cdtt_settings_widget.ui \
    ../../src/widgets/device_settings/choice_reaction_settings_widget.ui \
    ../../src/widgets/device_settings/dexa_settings_widget.ui \
    ../../src/widgets/device_settings/ecg_settings_widget.ui \
    ../../src/widgets/device_settings/frax_settings_widget.ui \
    ../../src/widgets/device_settings/grip_strength_settings_widget.ui \
    ../../src/widgets/device_settings/retinal_camera_settings_widget.ui \
    ../../src/widgets/device_settings/signature_pad_settings_widget.ui \
    ../../src/widgets/device_settings/spirometer_settings_widget.ui \
    ../../src/widgets/device_settings/tonometer_settings_widget.ui \
    ../../src/widgets/device_settings/vivid_i_settings_widget.ui \
    ../../src/widgets/device_settings/weight_scale_settings_widget.ui \
    ../../src/widgets/dicom_widget.ui \
    ../../src/widgets/directory_picker_widget.ui \
    ../../src/widgets/file_picker_widget.ui \
    ../../src/widgets/measurement_table.ui \
    ../../src/widgets/serial_port_picker_widget.ui \
    ../../src/widgets/serial_port_widget.ui \
    ../../src/widgets/settings_dialog.ui \
    ../../src/widgets/submission_buttons.ui \
    ../../src/widgets/test_info_widget.ui \
    ../../src/widgets/usb_port_picker.ui \
    ../../src/widgets/weight_scale_manual_entry_form.ui

DISTFILES += \
    ../../src/server/pages/index.html
