# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtWidgets
from PySide6.QtGui import QAction, QDoubleValidator
from PySide6.QtWidgets import QApplication, QSystemTrayIcon, QMenu

from ui.cypress_main_window import Ui_CypressMainWindow

import sys


class MainWindow(QtWidgets.QMainWindow, Ui_CypressMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.languageValue.addItem("En", "english")
        self.languageValue.addItem("Fr", "french")
        self.languageValue.setCurrentIndex(0)
        self.languageValue.currentTextChanged.connect(self.on_language_changed)

        self.uidValue.textChanged.connect(self.on_uid_text_changed)

        self.barcodeValue.textChanged.connect(self.on_barcode_text_changed)

        weight_validator = QDoubleValidator(bottom=0.00, top=999.99, decimals=2)
        self.weightValue.setValidator(weight_validator)
        self.weightValue.textChanged.connect(self.on_weight_text_changed)

        height_validator = QDoubleValidator(bottom=0.00, top=999.99, decimals=2)
        self.heightValue.setValidator(height_validator)
        self.heightValue.textChanged.connect(self.on_height_text_changed)

        self.dateOfBirthValue.dateChanged.connect(self.on_date_of_birth_changed)

        self.sexValue.currentTextChanged.connect(self.on_sex_text_changed)

        self.setAllEnabled(True)

    def setAllEnabled(self, enabled: bool):
        self.languageValue.setEnabled(enabled)
        self.uidValue.setEnabled(enabled)
        self.barcodeValue.setEnabled(enabled)
        self.weightValue.setEnabled(enabled)
        self.heightValue.setEnabled(enabled)
        self.dateOfBirthValue.setEnabled(enabled)
        self.sexValue.setEnabled(enabled)

    def on_language_changed(self, language: str):
        print("Language changed!", language)

    def on_uid_text_changed(self, uid: str):
        print("UID changed!", uid)

    def on_barcode_text_changed(self, barcode: str):
        print("Barcode changed!", barcode)

    def on_weight_text_changed(self, weight: str):
        print("weight changed!", weight)

    def on_height_text_changed(self, height: str):
        print("height changed!", height)

    def on_date_of_birth_changed(self, date_of_birth: str):
        print("date of birth changed!", date_of_birth)

    def on_sex_text_changed(self, sex: str):
        print("sex changed!", sex)


def run_main_ui():
    app = QApplication(sys.argv)
    QApplication.setQuitOnLastWindowClosed(True)

    if not QSystemTrayIcon.isSystemTrayAvailable():
        print("No system tray is available")
        sys.exit(1)

    tray = QSystemTrayIcon()
    tray.setToolTip("Pypress")

    menu = QMenu()
    menu.addAction(QAction("Show window", triggered=lambda: print("Show")))
    menu.addAction(QAction("Quit", triggered=app.quit))

    #window = uic.loadUi("main.ui")
    main_window = MainWindow()
    main_window.show()

    sys.exit(app.exec())

if __name__ == "__main__":
    run_main_ui()
